### ISSUE TITLE
CAN on wrong micro pins

### ISSUE THREAD

**Issue by mawildoer** [atopile/spin-servo-drive#14]
CAN can't work on these pins and they don't match where we previously had it

https://www.st.com/resource/en/datasheet/stm32g431c6.pdf#page=56

```
    # CANBUS Comms
    can_ttl.rx ~ ic.PB5
    can_ttl.tx ~ ic.PB6
```

<img width="787" alt="Screenshot 2024-03-08 at 11 38 18" src="https://github.com/atopile/spin-servo-drive/assets/4241578/5b1cd839-bdd3-4711-bac6-de1604b444be">

**Comment by napowderly** [comment]
Updated in beta build
