### ISSUE TITLE
CAN bus control - Position, Velocity, Torque

### ISSUE THREAD

**Issue by napowderly** [atopile/spin-servo-drive#18]
Objective: Build a simple interface to send commands + receive status messages from motors.

SimpleFOC has a commander interface that will currently take serial commands
https://docs.simplefoc.com/commander_interface

Want to be as standard as possible, a few possible standards to follow/integrate with:
https://opencyphal.org/
https://legacy.uavcan.org/Specification/7._List_of_standard_data_types/
https://docs.odriverobotics.com/v/0.5.4/commands.html
https://github.com/mjbots/moteus/blob/main/docs/reference.md

**Comment by mawildoer** [comment]
Selected CANSimple. Implementing w/ #37
