### ISSUE TITLE
Buck gets hot + should be replaced with the one from the regulators lib

### ISSUE THREAD

**Issue by mawildoer** [atopile/spin-servo-drive#3]
It's commented out as of now, but needs to be reinstated https://github.com/atopile/spin-servo-drive/pull/2/files#diff-6e4ac9d361dfecf8519cc1b8b6745f2c045e5d59f2bceb5c548a9325fa491974R96-R99

**Comment by mawildoer** [comment]
Requires validation; have debug build of that

**Comment by napowderly** [comment]
Inductor sized incorrectly on first build, updated in next rev.
